pygments:               true
relative_permalinks:    false
repository:             https://github.com/cloudera/cm_api
url:                    /cm_api
google_analytics_id:    UA-2275969-20

safe:                   true
lsi:                    false
markdown:               kramdown

latest_api_version:     17
latest_cm_version:      5.12.0
